name: CI Pipeline 
on: [push, pull_request]

jobs:
    server-tests:
        runs-on: ubuntu-latest
        services:
          mongodb:
            image: mongo:6.0
            ports:
              - 27017:27017

        steps:
            - uses: actions/checkout@v4
            - name: install Node
              uses: actions/setup-node@v4
              with:
                node-version: 24
            - name: install Server Deps
              run: cd taskManager-server && npm install
            - name: Run Server Tests 
              run: cd taskManager-server && npm test 
    client-tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Install and Test client 
            run: | 
              cd taskManager-client
              npm install
              npm test
          